--1.	Definir un tipo varray de dimensión 3 para contener los teléfonos
CREATE OR REPLACE TYPE TIPO_TELEFONOS AS VARRAY(3) OF VARCHAR2(10);
--2.	Crear los tipos dirección, cliente, producto y el tipo  línea de venta
CREATE OR REPLACE TYPE TIPO_DIRECCION_CASA AS OBJECT
(
CALLE_CASA VARCHAR2(50),
LOCALIDAD_CASA VARCHAR2(50),
CODPOSTAL_CASA NUMBER(5)
);
CREATE OR REPLACE TYPE TIPO_DIRECCION_ENVIO AS OBJECT
(
CALLE_ENVIO VARCHAR2(50),
LOCALIDAD_ENVIO VARCHAR2(50),
CODPOSTAL_ENVIO NUMBER(5)
);
CREATE OR REPLACE TYPE TIPO_CLIENTE AS OBJECT
(
NIF VARCHAR2(9),
NOMBRE VARCHAR2(50),
TELEFONO TIPO_TELEFONOS,
DIRECCION_CASA TIPO_DIRECCION_CASA,
DIRECCION_ENTREGA TIPO_DIRECCION_ENVIO
);

CREATE OR REPLACE TYPE TIPO_PRODUCTO AS OBJECT
(
IDPRODUCTO NUMBER,
DESCRIPCION VARCHAR2(80),
PVP NUMBER,
STOCKACTUAL NUMBER
);

CREATE OR REPLACE TYPE TIPO_LINEA AS OBJECT
(
NUMEROLINEA NUMBER,
PRODUCTOS REF TIPO_PRODUCTO,
CANTIDAD NUMBER
);
--3.	Crear un tipo tabla anidada para contener las líneas de una venta:
CREATE OR REPLACE TYPE TIPO_LINEAS AS TABLE OF TIPO_LINEA;
--4.	Crear un tipo venta para los datos de las ventas, cada venta tendrá un atributo LINEAS del tipo tabla anidada definida anteriormente:
CREATE OR REPLACE TYPE TIPO_VENTA AS OBJECT
(
LINEAS TIPO_LINEAS,
IDVENTA NUMBER,
NIF REF TIPO_CLIENTE,
FECHAVENTA DATE
);

CREATE TABLE VENTAS OF TIPO_VENTA
(
PRIMARY KEY (IDVENTA),
NIF NOT NULL
)
NESTED TABLE LINEAS STORE AS ANIDADA ;

--5.	Crear las tablas donde almacenar los objetos de la aplicación. Se creará una tabla para clientes, otra para productos y
--otra para las ventas, en dichas tablas se definirán las oportunas claves primarias.
CREATE TABLE CLIENTES OF TIPO_CLIENTE
(
PRIMARY KEY (NIF)
);
CREATE TABLE PRODUCTOS OF TIPO_PRODUCTO
(
PRIMARY KEY (IDPRODUCTO)
);

--6.	Inserta dos clientes y cinco productos.
INSERT INTO CLIENTES VALUES ('11111111A','JOSE ANTONIO ACEVEDO PAREDES',TIPO_TELEFONOS('111111111','222222222'),TIPO_DIRECCION_CASA('CALLE UNO','DOMICILIO UNO',1),TIPO_DIRECCION_ENVIO('CALLE UNO','DOMICILIO UNO',1));
INSERT INTO CLIENTES VALUES ('22222222A','PEDRO LINARES BAEZA',TIPO_TELEFONOS('333333333','444444444'),TIPO_DIRECCION_CASA('CALLE DOS','DOMICILIO DOS',1),TIPO_DIRECCION_ENVIO('CALLE DOS','DOMICILIO DOS',1));

INSERT INTO PRODUCTOS VALUES (0,'PRIMERO',0,0);
INSERT INTO PRODUCTOS VALUES (1,'SEGUNDO',11,111);
INSERT INTO PRODUCTOS VALUES (2,'TERCERO',22,222);
INSERT INTO PRODUCTOS VALUES (3,'CUARTO',33,333);
INSERT INTO PRODUCTOS VALUES (4,'QUINTO',44,444);

--7.	Insertar en TABLA_VENTAS la venta con IDVENTA 1 para el IDCLIENTE 1
--Insertar en TABLA_VENTAS dos líneas de venta para el IDVENTA 1 para los productos 1 (la CANTIDAD es 1) y 2 (la CANTIDAD es 2)
INSERT INTO VENTAS VALUES 
(
TIPO_LINEAS(
TIPO_LINEA(1,(SELECT REF (P) FROM PRODUCTOS P WHERE IDPRODUCTO=1),1),
TIPO_LINEA(2,(SELECT REF (P) FROM PRODUCTOS P WHERE IDPRODUCTO=2),2)
),
1,
(SELECT REF(C) FROM CLIENTES C WHERE NIF='11111111A'),
'12-03-2021'
);

--8.	Insertar en TABLA_VENTAS la venta con IDVENTA 2 para el IDCLIENTE.
--Insertar en TABLA_VENTAS tres líneas de venta para el IDVENTA 2 para los 
--productos 1 (la CANTIDAD es 2), 4 (la CANTIDAD es 1) y 5 (la CANTIDAD es 4)

INSERT INTO VENTAS VALUES 
(
TIPO_LINEAS(
TIPO_LINEA(1,(SELECT REF (P) FROM PRODUCTOS P WHERE IDPRODUCTO=1),2),
TIPO_LINEA(1,(SELECT REF (P) FROM PRODUCTOS P WHERE IDPRODUCTO=4),1)
),
2,
(SELECT REF(C) FROM CLIENTES C WHERE NIF='22222222A'),
'12-03-2021'
);

INSERT INTO THE
(SELECT LINEAS FROM VENTAS WHERE IDVENTA=2)
VALUES (
TIPO_LINEA(2,(SELECT REF (P) FROM PRODUCTOS P WHERE IDPRODUCTO=2),4));

--9.	Consultar todas las  ventas:  IDVENTAS, NOMBRE DEL CLIENTE,  FECHA VENTA, DIRECCION_ENVIO

SELECT V.IDVENTA,DEREF(V.NIF).NOMBRE,V.FECHAVENTA,DEREF(V.NIF).DIRECCION_ENTREGA FROM VENTAS V ;

--10.	Consultar la líneas  de venta de la ventas 2. DESCRIPCION DEL PRODUCTO, CANTIDAD, PVP DEL PRODUCTO E IMPORTE. 
--IMPORTE ES EL RESULTADO DE MULTIPLICAR CANTIADAD POR PVP)
SELECT V.IDVENTA,CURSOR
(SELECT DEREF(PRODUCTOS).IDPRODUCTO AS IDPRODUCTO,
DEREF(PRODUCTOS).DESCRIPCION AS DESCRIPCION,
DEREF(PRODUCTOS).PVP AS PVP,
CANTIDAD,
DEREF(PRODUCTOS).PVP * CANTIDAD AS IMPORTE
FROM TABLE(V.LINEAS) WHERE IDVENTA=2) AS DATOS
FROM VENTAS V WHERE V.IDVENTA=2;

